// The CSS custom properties must be in a stylesheet — they apply during HTML
// parse, before React loads, which is what makes the portal render themed on
// first paint. But the tokens are declared in TypeScript. Generating the CSS
// keeps one source of truth; `pnpm themes:css --check` fails if they diverge.
//
// Run with `tsx`, not `node --experimental-strip-types`. Type stripping does not
// remap the `.js` import specifiers this project uses inside `src/` back to
// `.ts`/`.tsx` (the same limitation scripts/dev-demo.sh documents for the
// server), so the registry's `./classic/index.js` import cannot be resolved, and
// the JSX it pulls in transitively would not compile either.
import { readFileSync, writeFileSync } from 'node:fs'
import { listThemes } from '../src/web/themes/registry.ts'
import { tokensToCss } from '../src/web/themes/tokens.ts'

const OUT = 'src/web/themes/generated.css'

const css = [
  '/* GENERATED by scripts/generate-theme-css.ts — do not edit by hand. */',
  '/* Regenerate with: pnpm themes:css */',
  '',
  ...listThemes().flatMap((theme) => [
    `[data-theme='${theme.id}'] {`,
    tokensToCss(theme.tokens.light),
    '}',
    '@media (prefers-color-scheme: dark) {',
    `  [data-theme='${theme.id}'] {`,
    tokensToCss(theme.tokens.dark),
    '  }',
    '}',
    '',
  ]),
].join('\n')

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf-8')
  if (current !== css) {
    console.error(`${OUT} is stale. Run: pnpm themes:css`)
    process.exit(1)
  }
  console.log(`${OUT} is up to date`)
} else {
  writeFileSync(OUT, css)
  console.log(`wrote ${OUT}`)
}
