// The CSS custom properties must be in a stylesheet — they apply during HTML
// parse, before React loads, which is what makes the portal render themed on
// first paint. But the tokens are declared in TypeScript. Generating the CSS
// keeps one source of truth; `pnpm themes:css --check` fails if they diverge.
//
// Run with `tsx`, not `node --experimental-strip-types`. Type stripping does not
// remap the `.js` import specifiers this project uses inside `src/` back to
// `.ts`/`.tsx` (the same limitation scripts/dev-demo.sh documents for the
// server).
//
// This deliberately does NOT import the theme registry. The registry pulls in
// every theme's components, and components are built by Vite — so a theme using
// any Vite-only feature (`?raw`, `?url`, an asset import) would break CSS
// generation under plain Node, with an error pointing at this script rather than
// at the import that caused it. That is an invisible constraint on what a theme
// may contain, and it already cost the `cards` theme its icon imports.
//
// Instead each theme's `tokens.ts` is loaded directly. Those are pure data with
// a type-only import, so they load anywhere, and a theme's components stay free
// to use whatever Vite supports. The directory listing is the source of truth
// for which themes exist — the same "the file IS the registration" rule the
// preview images follow — and it is cross-checked against THEME_IDS below, so
// this script also catches a theme folder that was never declared, or declared
// and never written.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { THEME_IDS, isThemeId } from '../src/shared/themes.ts'
import { type ThemeTokens, tokensToCss } from '../src/web/themes/tokens.ts'

const THEMES_DIR = 'src/web/themes'
const OUT = `${THEMES_DIR}/generated.css`

const discovered = readdirSync(THEMES_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && entry.name !== 'default')
  .map((entry) => entry.name)
  .sort()

const undeclared = discovered.filter((name) => !isThemeId(name))
if (undeclared.length > 0) {
  console.error(`theme folders not in THEME_IDS: ${undeclared.join(', ')}`)
  process.exit(1)
}

const missing = THEME_IDS.filter((id) => !discovered.includes(id))
if (missing.length > 0) {
  console.error(`themes declared in THEME_IDS but not implemented: ${missing.join(', ')}`)
  process.exit(1)
}

const blocks: string[] = []
for (const id of discovered) {
  const { light, dark } = (await import(`../${THEMES_DIR}/${id}/tokens.ts`)) as {
    light: ThemeTokens
    dark: ThemeTokens
  }

  blocks.push(
    `[data-theme='${id}'] {`,
    tokensToCss(light),
    '}',
    '@media (prefers-color-scheme: dark) {',
    `  [data-theme='${id}'] {`,
    tokensToCss(dark),
    '  }',
    '}',
    '',
  )
}

const css = [
  '/* GENERATED by scripts/generate-theme-css.ts — do not edit by hand. */',
  '/* Regenerate with: pnpm themes:css */',
  '',
  ...blocks,
].join('\n')

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT, 'utf-8')
  if (current !== css) {
    console.error(`${OUT} is stale. Run: pnpm themes:css`)
    process.exit(1)
  }
  console.log(`${OUT} is up to date`)
} else {
  writeFileSync(OUT, css)
  console.log(`wrote ${OUT}`)
}
